# Generated by Django 3.0.5 on 2020-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('fee', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('dateofbirth', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('courses', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
